### PR TITLE
Revisions

### PR DESCRIPTION
**Pull request by daronyondem**

### CODE REVIEW

**Comment by daronyondem** [comment]
@srushti-714 can you take a look at the changes in this PR and let me know if you see any issues. 

Thanks

**Comment by srushti-714** [comment]
Hi @daronyondem 

The values required for Exercise 2 Bonus Challenge notebook  will already be replaced in 00.Setupworkspace.md (as a part of pre-requisite)

You can add a note like:
Replace the value if not already 
image

**Comment by daronyondem** [comment]
Done @srushti-714, take another look. Thanks.

**Comment by srushti-714** [comment]
Hi @daronyondem 

The notebook has many values to be replaced which will already be done as a part of setup ,can you remove it from the instruction?

00-Setupworkspace
https://spektrasystems.sharepoint.com/:x:/r/sites/CloudLabsAITeamHub/_layouts/15/guestaccess.aspx?e=K0lKhP&share=EXSo3FHfmEhDmxVVLjVW89wBM-IqI1UCpxTQ5vWFwLWsrQ

**Comment by srushti-714** [comment]
@daronyondem  Could you please check and update
https://github.com/solliancenet/azure-synapse-analytics-day/issues/13

**Comment by daronyondem** [comment]
Hi @srushti-714 

I'm not sure what instruction you are referring to. To clear things up, if you do not have any rejection of the changes suggested in the pull request I suggest we merge this one first.

I'm moving the issue here #16 

Let me know if you see any problems with the changes suggested in this pull request.

**Comment by daronyondem** [comment]
@srushti-714 Any feedback about the changes introduced in this PR? Unless we merge this, the changes will not go live.

**Comment by srushti-714** [comment]
Hi @Daron Yöndem<mailto:daron@solliance.net>

After testing out in an environment
I have added the correct screenshot  for chart view and instruction in https://github.com/solliancenet/azure-synapse-analytics-day/issues/7

Apart from this no other change needs to be done.

Thanks,
Srushti

**Pull request merged**
